// <auto-generated />
namespace DCC_Planned_Derived_Ventures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedachangetoitineraryaddressmodelinhopetoseetableaddedtodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedachangetoitineraryaddressmodelinhopetoseetableaddedtodb));
        
        string IMigrationMetadata.Id
        {
            get { return "201808022057388_added a change to itineraryaddress model in hope to see table added to db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
