// <auto-generated />
namespace DCC_Planned_Derived_Ventures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingmigrationsoIcanseedstates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingmigrationsoIcanseedstates));
        
        string IMigrationMetadata.Id
        {
            get { return "201808012134473_adding migration so, I can seed states"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
